### ISSUE TITLE
python ImportError

### ISSUE THREAD

**Issue by iamweifan** [CoreSecurity/pcapy#39]
import pcapy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win32\egg\pcapy.py", line 7, in <module>
  File "build\bdist.win32\egg\pcapy.py", line 6, in __bootstrap__
ImportError: DLL load failed: 找不到指定的模块。

Winpcap has already in my computer

**Comment by Tusaka** [comment]
I meet this problem too, have you solved it ? Thank you very much.

**Comment by user2589** [comment]
@iamweifan ,

I couldn’t find a better way to contact you so I’m writing here. This comment will be deleted in one week to keep the issue discussion clean.

My name is Marat, I am a PhD student at Carnegie Mellon University. As a part of my research, I’m trying to better understand the sources of issue reports in open source.

Can you please help me by answering few questions about this issue? It shouldn’t take more than a couple of minutes. Here’s the google form: [link](https://docs.google.com/forms/d/e/1FAIpQLSfTlhMeh25AZAr0wy-DNBki_HzFP_fqdT3eIk1mf7b80mg8Lg/viewform?usp=pp_url&entry.2074867396=https://github.com/SecureAuthCorp/pcapy/issues/39)

I will share everything I learn from answers to this survey with the community afterwards.

Thank you very much!

**Comment by JohnTroony** [comment]
Did you correctly install and point the [WinPcap Dev Kit](http://www.winpcap.org/install/bin/WpdPack_4_1_2.zip) libraries on your setup.py before compiling?
