### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by greenpau** [CoreSecurity/pcapy#9]
pip install fails with the below message.

```
[root@default /]# pip3 install pcapy
Collecting pcapy
  Downloading pcapy-0.10.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-qwu_r00b/pcapy/setup.py", line 43
        print 'my_init_posix: changing LDSHARED =',`g['LDSHARED']`,
                                                 ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qwu_r00b/pcapy
[root@default /]# 
```

**Comment by dajose22** [comment]
That's python 2.x syntax and it wont work with python 3.x. Check issue #3

**Comment by guihubxiaoming** [comment]
Can describe the question in detail?

**Comment by guihubxiaoming** [comment]
Can you describe the question in detail?
